# YN April 2018
#
# Updated January 2025 to read files generated by spr_PlotKineticsSutracted_2Plots_Improved.py
# Script to fit SPR affinity data
# Works with *SteadyState.txt files
# Ex: python ~/RESEARCH/SCRIPTS/spr_AffinityFit4FA.py -Rmin=0.01 -mc=100 -noise=5. -norm=1

import sys,os,re,argparse,math
from random import gauss
from scipy import optimize as o
import numpy as np
import matplotlib.pylab as plt
import matplotlib.ticker as plticker


def LoadData(file,norm):
    FILE = open(file, 'r')
    all_lines = FILE.readlines()
    #print(all_lines)
    X = []; Y = []; N = []
    for line in all_lines[1:]:
        #line=line.replace(',','.')
        #print line
        #linesplit=line.split("\t")
        linesplit = re.split(r'\s+', line)
        print(linesplit)
        if (linesplit[0]):
            X.append(float(linesplit[0])*1e-6)
            Y.append(float(linesplit[1]))
            if (norm == 1):
                #print(linesplit, len(linesplit))
                if (len(linesplit) != 5):
                    print("Data file must contained peptide immobilization level in the 3rd column")
                else:
                    N.append(float(linesplit[2]))
    X=np.array(X)
    Y=np.array(Y)
    print(X)
    print(Y)
    MeanImmob = 1.
    if (norm == 1):
        N=np.array(N)
        MeanImmob = np.mean(N)
        print(N)
        Y=Y/N
    return(X,Y,MeanImmob)

def FitFit(X,Y,fun):
    residuals = lambda PAR, X, Y, fun: Y - COMPLEX(X, PAR)    
    (v, cov_v) = o.leastsq(residuals, PAR, args=(X, Y, COMPLEX))
    #print(v, cov_v)
    return v

def FitFitRM(X,Y,fun):
    residuals = lambda PAR, X, Rmax, Y, fun: Y - COMPLEX(X, Rmax, PAR)    
    (v, cov_v) = o.leastsq(residuals, PAR, args=(X, Rmax, Y, COMPLEX))
    #print(v, cov_v)
    return v

def FitFitRm(X,Y,fun):
    residuals = lambda PAR, X, Rmin, Y, fun: Y - COMPLEX(X, Rmin, PAR)    
    (v, cov_v) = o.leastsq(residuals, PAR, args=(X, Rmin, Y, COMPLEX))
    #print(v, cov_v)
    return v

def Noiser(Val, Noise):
    Data = []
    for val in Val: Data.append(gauss(val, Noise))
    Data = np.array(Data)
    return Data
 

#############################################################
if '__main__' == __name__:
    #python spr_AffinityFit4IS.py -file=241216_D_p38_Fc2-1corr_2HPwt_SteadyState.txt -mc=1000
    #python spr_AffinityFit4IS.py -file=240408_D_p108a_Fc4-1corr_DblRef_2HPnewHigh_SteadyState.txt -mc=1000
    print("Possible to define arguments.")
    print("ex: python spr_AffinityFit4AB.py -file=FileName.txt -Rmax=135.")
    
    parser = argparse.ArgumentParser()
    parser.add_argument('-file' , '--File' , help="FileName")
    parser.add_argument('-Rmax' , '--Fixed_Rmax' , default=[] , type=float, help="RMax can be fixed in the fit")
    parser.add_argument('-Rmin' , '--Fixed_Rmin' , default=-100 , type=float, help="RMin can be fixed in the fit")
    parser.add_argument('-norm' , '--Normalization' , default=0 , type=int, help="Default: 0; 1 if normalization by immobilized peptide")
    parser.add_argument('-mc' , '--Monte_Carlo' , default=0 , type=int, help="Number of cycles for the Monte Carlo analysis; default:0")
    #parser.add_argument('-noise' , '--Noise_Signal' , default=1.0 , type=float, help="Noise value to run Monte Carlo analysis")
    args = parser.parse_args()
    print(args)
    
    file = args.File
    Rmax = args.Fixed_Rmax
    Rmin = args.Fixed_Rmin
    print('Rmin : ', Rmin)
    norm = args.Normalization
    mc = args.Monte_Carlo
    #Noise = args.Noise_Signal
    
    plt.close()
    print(norm)
    (X,Y,MeanImmob)=LoadData(file,norm)
    
    # Search for duplicated concentrations and calculate the STD of RU signal
    noiseVal = []
    for i in range(len(X)-1,-1,-1):
        for j in range(i-1,-1,-1):
            if X[j] == X[i]:
                noiseVal.append(np.abs((Y[i]-Y[j])/2))
    if noiseVal:
        Noise = max(noiseVal)/MeanImmob
    else: Noise = 1./MeanImmob
    print('Noise = ',Noise)
    
    Conc = np.logspace(-7,-2,1000)
    KD = 1.e-6
    RUmin = 0
    RUmax = np.max(Y)
    Upper = 100.
    par = []
    Data=[]
    
    
    if Rmax:
        print("")
        print("Rmax argument fixed")
        PAR=np.array([KD, RUmin])
        print('Rmax = ',Rmax)
        COMPLEX = lambda PDZ, Rmax, PAR: PAR[1]+(Rmax-PAR[1])*(PDZ/(PDZ+PAR[0]))
        fun = COMPLEX
        print(PAR)
        v = FitFitRM(X,Y,fun)
        Ssim = COMPLEX(Conc, Rmax, PAR)
        Smod = COMPLEX(Conc, Rmax, v)
        Sfit = COMPLEX(X,Rmax,v)
        if mc != 0:
            for i in range(0,mc):
                Yn = Noiser(Y,Noise)
                ParamMc = FitFitRM(X, Yn, fun)
                par.append(ParamMc)
            par = np.array(par)
            print("#mc loops:", mc)
            PAROPTmc = np.mean(par, axis=0)
            PARSTDmc = np.std(par, axis=0)    
    elif Rmin != -100.:
        print("")
        print("Rmin argument fixed")
        PAR=np.array([KD, RUmax])
        print('Rmin = ',Rmin)
        COMPLEX = lambda PDZ, Rmin, PAR: Rmin+(PAR[1]-Rmin)*(PDZ/(PDZ+PAR[0]))
        fun = COMPLEX
        print(PAR)
        v = FitFitRm(X,Y,fun)
        Ssim = COMPLEX(Conc, Rmin, PAR)
        Smod = COMPLEX(Conc, Rmin, v)
        Sfit = COMPLEX(X,Rmin,v)
        if mc != 0:
            for i in range(0,mc):
                Yn = Noiser(Y,Noise)
                ParamMc = FitFitRm(X, Yn, fun)
                par.append(ParamMc)
            par = np.array(par)
            print("#mc loops:", mc)
            PAROPTmc = np.mean(par, axis=0)
            PARSTDmc = np.std(par, axis=0)    
    else :
        PAR=np.array([KD, RUmin, RUmax])
        COMPLEX = lambda PDZ, PAR: PAR[1]+(PAR[2]-PAR[1])*(PDZ/(PDZ+PAR[0]))
        fun = COMPLEX
        print(PAR)
        v = FitFit(X,Y,fun)
        Ssim = COMPLEX(Conc, PAR)
        Smod = COMPLEX(Conc, v)
        Sfit = COMPLEX(X,v)
        if mc != 0:
            for i in range(0,mc):
                Yn = Noiser(Y,Noise)
                ParamMc = FitFit(X, Yn, fun)
                par.append(ParamMc)
            par = np.array(par)
            print("#mc loops:", mc)
            PAROPTmc = np.mean(par, axis=0)
            PARSTDmc = np.std(par, axis=0)    

    print("ParamOpt :                ", v)
    Diff=Y-Sfit
    Rmsd = np.sqrt(np.dot(Diff,Diff)/len(X))
    print("SquareRoot_Of_Chi2 for un-normalized data= ",Rmsd)
    if mc != 0:
        print("#mc loops:", mc)
        print("Mean of ParamOpt after MC:", PAROPTmc)
        print("STD of ParamOpt after MC: ", PARSTDmc)
        if Rmin != -1000.:
            print(file.split('.')[0], PAROPTmc[0], PARSTDmc[0], PAROPTmc[1], PARSTDmc[1], Rmsd)
        else :
            print(file.split('.')[0], PAROPTmc[0], PARSTDmc[0], PAROPTmc[1], PARSTDmc[1], PAROPTmc[2], PARSTDmc[2], Rmsd)
    
    #ax = plt.subplot(211)
    #ax.set_xscale('log')
    #plt.plot(Conc, Ssim, '-g', label='Simulated data')
    ax = plt.subplot(212)
    ax.set_xscale('log')
    if (norm == 1):
        majorLocator = plticker.MultipleLocator(base = 10.)
        minorLocator = plticker.MultipleLocator(5)
    else:
        majorLocator = plticker.MultipleLocator(base = 100.)
        minorLocator = plticker.MultipleLocator(50)
    ax.yaxis.set_major_locator(majorLocator)
    ax.yaxis.set_minor_locator(minorLocator)
    plt.plot(X, Y, 'or', label=file)
    plt.plot(Conc, Smod, '-k', label='Fitted Model')
    #plt.legend()
    plt.axis([3e-7,1e-3,-20,Upper/MeanImmob])
    plt.title('SPR')
    TXT0 = file.split('.')[0]
    if mc != 0:
      TXT1 = "KD (uM): %6.2f ± %6.2f" %(PAROPTmc[0]*1e6,PARSTDmc[0]*1e6)
      TXT2 = "Rmax: %6.1f ± %6.1f" %(PAROPTmc[2],PARSTDmc[2])
      TXT3 = "Rmin: %6.2f ± %6.2f" %(PAROPTmc[1],PARSTDmc[1])
    else:
      TXT1 = "KD (uM): %6.2f" %(v[0]*1e6)
      TXT2 = "Rmax: %6.1f" %(v[2])
      TXT3 = "Rmin: %6.2f" %(v[1])
      
    TXT4 = "RMSD: %4.3f" %(Rmsd)
    TXT5 = "Noise: %4.3f" %(Noise)
    plt.text(5e-7, 0.85*Upper, TXT0, fontsize=5)
    plt.text(5e-7, 0.75*Upper, TXT1, fontsize=5)
    plt.text(5e-7, 0.65*Upper, TXT2, fontsize=5)
    plt.text(5e-7, 0.55*Upper, TXT3, fontsize=5)
    plt.text(5e-7, 0.45*Upper, TXT4, fontsize=5)
    plt.text(5e-7, 0.35*Upper, TXT5, fontsize=5)
    
    
    FigName = file.split('.')[0] + '.eps'
    print(FigName)
    plt.savefig(FigName)
    plt.show()
